# Minimal stub for pypdfium2 — covers only the surface
# `parse/vlm_backend.py` + `parse/chart_ocr_backend.py` use:
# `PdfDocument(path)`, `len(doc)`, `doc[idx]`, `doc.close()`,
# `page.get_width()`, `page.get_height()`, `page.render(scale=...)`,
# `bitmap.to_pil()`. pypdfium2 ships no `py.typed`.
from PIL import Image

class PdfBitmap:
    def to_pil(self) -> Image.Image: ...

class PdfPage:
    def get_width(self) -> float: ...
    def get_height(self) -> float: ...
    def render(self, scale: float = ..., **kwargs: object) -> PdfBitmap: ...

class PdfDocument:
    def __init__(self, input: str | bytes, **kwargs: object) -> None: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> PdfPage: ...
    def close(self) -> None: ...
