"""Audit 2026-05-22 follow-up to P3.3 v6 — pin `max_length` bounds on
LLM-emit string schemas.

v6 surfaced one schema-validation crash on Qwen3-4B-AWQ: the
`SufficiencyAssessment.reason` field was unbounded, and on a
counterfactual query the model rambled for ~2000 chars in `reason`,
exceeding `max_tokens=640` mid-string. JSON validation failed; the
whole eval aborted. The fix bounded `reason` to `max_length=500`.

This same pathology can fire on any unbounded LLM-emit string field.
The follow-up audit identified five candidates:

1. `DraftAnswer.summary` — answer node, "one or two sentences" emit
2. `CitedClaim.claim` — answer node, per-claim text
3. `VerificationResult.ungrounded_reasons` items — verify node, per-claim
   explanation. **RESOLVED DIFFERENTLY 2026-06-06:** the guided-decode backend
   does NOT reliably enforce string `max_length` at decode time — a 1-claim
   verify whose reason ran 1218+ chars truncated the JSON → `ModelCallError`
   (the slide-decks eval / `/ask` crash). So this free-text field was moved OFF
   the decode path entirely: the verifier emits the reason-less `VerifyIndices`,
   and reasons are code-generated by the deterministic backstops. Pinned by
   `test_verify_guided_schema_excludes_free_text_reasons`.
4. `ExtractedEntity.name` — enrich entity extraction
5. `ExtractedEntity.span_text` — enrich entity extraction

These tests pin the `max_length` bound on each field as POST-HOC pydantic
validation. NB the earlier belief that "xgrammar enforces these at the grammar
level so the LLM literally cannot emit a longer string" proved UNRELIABLE for the
verify reasons (#3) — treat the bounds as validation, not a decode-time guarantee.
The durable defense for ramble-prone free text is to keep it OFF the guided-decode
path (as #3 now is) plus the eval-runner / verify-node fail-closed try/except
(2026-06-06).
"""

from __future__ import annotations

import pytest
from pydantic import ValidationError

from memex.agents.answering import (
    CitedClaim,
    DraftAnswer,
    SufficiencyAssessment,
)
from memex.enrich.entities import ExtractedEntity


def test_sufficiency_assessment_reason_rejects_over_max_length() -> None:
    """v6's original fix — pin the bound that fixed the eval crash."""
    SufficiencyAssessment(sufficient=True, reason="ok"[:500])
    with pytest.raises(ValidationError) as exc:
        SufficiencyAssessment(sufficient=False, reason="x" * 501)
    assert "at most 500" in str(exc.value).lower() or "max_length" in str(exc.value)


def test_cited_claim_claim_rejects_over_max_length() -> None:
    """Per-claim runaway: each claim is "one factual statement" — 300
    chars is plenty (Path C tightening fits worst-case schema output
    within max_tokens=1024). Bound prevents per-claim ramble
    exhausting max_tokens before the claims list closes."""
    CitedClaim(claim="x" * 300, source_chunk_id="abc", confidence="high")
    with pytest.raises(ValidationError):
        CitedClaim(claim="x" * 301, source_chunk_id="abc", confidence="high")


def test_cited_claim_source_chunk_id_rejects_over_max_length() -> None:
    """Path C: source_chunk_id is bounded so a hallucinated chunk_id
    (e.g. model dumping chunk text into the id field) can't run away.
    Real chunk_ids are ~40 chars (sha1[:10] + slug); 80 is headroom."""
    CitedClaim(claim="ok", source_chunk_id="x" * 80, confidence="high")
    with pytest.raises(ValidationError):
        CitedClaim(claim="ok", source_chunk_id="x" * 81, confidence="high")


def test_draft_answer_summary_rejects_over_max_length() -> None:
    """The summary is the headline answer; the cap is a safety ceiling (the prompt
    still asks for 1-2 sentences). Raised 300→600 (2026-05-28) after full mode's
    deeper retrieval gave the model enough context to write a thorough answer that
    hit exactly 300 and was force-closed MID-WORD by xgrammar ("…policyEn"). The
    answer node raises max_tokens to match so the bigger output still closes."""
    DraftAnswer(summary="x" * 600, claims=[])
    with pytest.raises(ValidationError):
        DraftAnswer(summary="x" * 601, claims=[])


def test_draft_answer_claims_list_bounded() -> None:
    """Top-k retrieval surfaces 5 chunks; the answer model legitimately
    emits ~5 claims (one per chunk). Cap at 8 (Path C tightening)
    keeps worst-case schema output under max_tokens=1024."""
    DraftAnswer(
        summary="ok",
        claims=[
            CitedClaim(claim=f"c{i}", source_chunk_id=f"id{i}", confidence="high") for i in range(8)
        ],
    )
    with pytest.raises(ValidationError):
        DraftAnswer(
            summary="ok",
            claims=[
                CitedClaim(claim=f"c{i}", source_chunk_id=f"id{i}", confidence="high")
                for i in range(9)
            ],
        )


def test_extracted_entity_name_bounds() -> None:
    """Entity name legitimately runs 3-50 chars; 120 covers long
    org names or multi-word concepts. min_length=1 (existing
    constraint) + max_length=120 (new bound)."""
    ExtractedEntity(name="x", kind="person", confidence="high")
    ExtractedEntity(name="x" * 120, kind="person", confidence="high")
    with pytest.raises(ValidationError):
        ExtractedEntity(name="", kind="person", confidence="high")
    with pytest.raises(ValidationError):
        ExtractedEntity(name="x" * 121, kind="person", confidence="high")


def test_extracted_entity_span_text_bounds() -> None:
    """Quoted phrase from passage — 200 chars covers a long
    sentence fragment without enabling whole-paragraph emission."""
    ExtractedEntity(name="Alice", kind="person", confidence="high", span_text="x" * 200)
    with pytest.raises(ValidationError):
        ExtractedEntity(
            name="Alice",
            kind="person",
            confidence="high",
            span_text="x" * 201,
        )


def test_extracted_entity_span_text_default_empty_is_ok() -> None:
    """The default empty `span_text` is valid (some entities don't
    have an addressable span in the passage)."""
    e = ExtractedEntity(name="Alice", kind="person", confidence="high")
    assert e.span_text == ""


def test_verify_guided_schema_excludes_free_text_reasons() -> None:
    """The verifier's guided-decode schema is the reason-less `VerifyIndices`
    (2026-06-06 fix): the backend doesn't enforce string max_length at decode, so a
    model-emitted reason can ramble past max_tokens and truncate the JSON. Reasons
    are code-generated by the deterministic backstops, so the free-text field must
    stay OFF the decode path. The in-code `VerificationResult` keeps the field."""
    from memex.agents.answering import VerificationResult, VerifyIndices
    from memex.agents.grounding import bounded_verification

    assert set(VerifyIndices.model_fields) == {"grounded", "ungrounded"}
    assert "ungrounded_reasons" not in VerifyIndices.model_fields
    # the bounded schema actually sent to vLLM must also exclude it (field + JSON schema)
    bounded = bounded_verification(5)
    assert "ungrounded_reasons" not in bounded.model_fields
    assert "ungrounded_reasons" not in bounded.model_json_schema().get("properties", {})
    # the in-code RESULT keeps the field (deterministic-backstop reasons live here)
    assert "ungrounded_reasons" in VerificationResult.model_fields
